### ISSUE TITLE
Running example in docker container fails

### ISSUE THREAD

**Issue by smits** [signalogic/SigSRF_SDK#4]
When testing the demo app in the docker container I get the following errors:

 mediaMin/mediaMin -cx86 -i ./pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11

[...]
DSGetInstance: hCard or hDataPlane is not a valid handle, hCard = 0, num handles in use = 2
00:00:00.050.990 Error: DSCreateSession, invalid data plane handle when creating session, handle = 0
Failed to create dynamic session, app thread 0
[...]

What could be the cause of this and how can I resolve it?

The full output: 

mediaMin: packet media streaming for analytics and telecom applications on x86 and coCPU platforms v3.4.9
Copyright (C) Signalogic 2018-2024
  SigSRF libraries in use: DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, derlib v1.3.0, alglib v1.2.6, diaglib v1.7.0, cimlib v2.1.1
userSpecified = {Platform Designator = x86, Clock = 2592.000 MHz, coCPU Core List = N/A, coCPU Executable = N/A}
cimGetCmdLine:  Platform designator = x86
                Number of concurrent streams = 1
                Config file =
                Input RTP file[0] is ./pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap
                Buffer add interval [0] (msec) = -nan
                Source IP addr[0] = 0xa000165, port[0] = 10240, MAC addr[0] = ffeeddccbb
                Destination IP addr[0] = 0xa00010a, port[0] = 45056, MAC addr[0] = aabbccddee
                Mode[0] = one-shot:  load file, run
                Transfer mode[0] = File download
mediaMin start, cmd line execution
 Standard Operating Mode
  dynamic sessions created as they appear in stream input
  each input may contain one or more streams (each input is a "stream group")
 Test Modes
  none
 Options
  stream group(s) enabled
  wav file output for stream group(s) enabled
  Telecom mode with -rN nominal rate enabled
  packet arrival times control packet push rate
00:00:00.000.021 mediaMin INFO: event log setup complete, log file EVS_16khz_13200bps_CH_PT127_IPv4_event_log.txt, log level 8, cmd line mediaMin/mediaMin -cx86 -i ./pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11
00:00:00.000.110 INFO: DSAssignPlatform() says system clock rate 2592.000 MHz, CPU architecture supports rdtscp instruction, TSC integrity monitoring enabled
00:00:00.000.170 INFO: DSConfigPktlib() uflags = 0x7
  P/M thread capacity  max sessions = 51, max groups = 17
  Event log            path = EVS_16khz_13200bps_CH_PT127_IPv4_event_log.txt, uLogLevel = 8, uEventLogMode = 0x32, flush size = 1024, max size not set
  Debug                uDebugMode = 0x0, uPktStatsLogging = 0xd, uEnableDataObjectStats = 0x1
  Screen output        uPrintfLevel = 5, uPrintfControl = 0
  Energy saver         p/m thread energy saver inactivity time = 30000 msec, sleep time = 1000 usec
  Alarms               DSPushPackets packet cutoff alarm elapsed time not set, p/m thread preemption alarm elapsed time = 40 (msec)
00:00:00.000.532 INFO: DSConfigVoplib() voplib and codec libs initialized, flags = 0x19
00:00:00.000.558 INFO: DSConfigStreamlib() stream group library initialized
00:00:00.000.597 INFO: DSOpenPcap() opened pcap input file: ./pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap
Starting 1 packet and media processing threads
00:00:00.000.786 INFO: DSConfigMediaService() says pthread_setaffinity_np() set core 0 affinity for pkt/media thread 0 (thread id 0x7f510c537700), num online cores found = 16, uFlags = 0x1180101, pktlib.c:9782
x86 pkt/media start, pktlib, thread execution, thread id = 0x7f510c537700
00:00:00.000.895 INFO: first packet/media thread running, lib versions DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, alglib v1.2.6, diaglib v1.7.0
00:00:00.000.935 INFO: DSConfigMediaService() says setpriority() set Niceness to -15 for pkt/media thread 0
00:00:00.000.957 INFO: initializing packet/media thread 0, uFlags = 0x1180101, threadid = 0x7f510c537700, total num pkt/med threads = 1
lib_dbg_cfg.uPrintfLevel = 5
lib_dbg_cfg.uLogLevel = 8
lib_dbg_cfg.uPrintfControl = 0
lib_dbg_cfg.uEventLogMode = 0x32
lib_dbg_cfg.uEventLogFile = 0x0x5571eb0
lib_dbg_cfg.uPktStatsLogging = 0xd
thread mode, nSessions_gbl = 0
Static session initialization: 0 sessions and 0 stream terminations
                                                Pkts recv 0%s   mnp -1 -1 -1 pd -1.00 -1.00 -1.00
Starting packet push-pull loop, press 'q' to exit, 'd' for real-time debug output, and other keys as described in online documentation
^^^^^^^ Creating dynamic session 1, input #1, auto-detected codec type EVS, auto-detected bitrate 13200, stream group EVS_16khz_13200bps_CH_PT127_IPv4
        Creation packet info: IP ver 4, ssrc = 0x841aa8, seq num = 2, payload type 127, pkt len 73, RTP payload size 33, cat 4, rtp_pkt[0] 0x8b, src port = 52992, dst_port = 10240
DSGetInstance: hCard or hDataPlane is not a valid handle, hCard = 0, num handles in use = 2
00:00:00.050.990 Error: DSCreateSession, invalid data plane handle when creating session, handle = 0
Failed to create dynamic session, app thread 0
Total sessions created = 0, deleted = 0
Num pkts recv = 0
x86 pkt/media thread end
mediaThread app end

**Comment by signalogic** [comment]
Hi Ruben, try this command:

  `rm /dev/shm/hwlib*`

then run mediaMin again.  If there was a prior crash in mediaMin or mediaTest, some shared mem files may be left over or get corrupted **. Were you able to run mediaMin commands before ? If so and then after some time you got this error message then this is likely the issue

** these files allow multiple process to run mediaMin and mediaTest concurrently

**Comment by smits** [comment]
Ok, thx, all seems to work now.

**Comment by signalogic** [comment]
ok sounds good, any problems running your own pcaps please don't hesitate to ask

**Comment by smits** [comment]
It works for some pcaps, but for one I get the following error: 
/home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin: symbol lookup error: /lib/libevscom_sig.x86_gcc11.3.so: undefined symbol: _ZGVbN2v_acos

**Comment by smits** [comment]
In some pcap files the above error is prepended with the following:
```
/home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin -cx86 -i ./target1561_session2331694_0000.pcap -L -d0xc11 -r20
mediaMin: packet media streaming for analytics and telecom applications on x86 and coCPU platforms v3.4.9
Copyright (C) Signalogic 2018-2024
  SigSRF libraries in use: DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, derlib v1.3.0, alglib v1.2.6, diaglib v1.7.0, cimlib v2.1.1
userSpecified = {Platform Designator = x86, Clock = 2592.000 MHz, coCPU Core List = N/A, coCPU Executable = N/A}
cimGetCmdLine:  Platform designator = x86
                Number of concurrent streams = 1
                Config file =
                Input RTP file[0] is ./target1561_session2331694_0000.pcap
                Buffer add interval [0] (msec) = 20.00
                Source IP addr[0] = 0xa000165, port[0] = 10240, MAC addr[0] = ffeeddccbb
                Destination IP addr[0] = 0xa00010a, port[0] = 45056, MAC addr[0] = aabbccddee
                Mode[0] = one-shot:  load file, run
                Transfer mode[0] = File download
mediaMin start, cmd line execution
 Standard Operating Mode
  dynamic sessions created as they appear in stream input
  each input may contain one or more streams (each input is a "stream group")
 Test Modes
  none
 Options
  stream group(s) enabled
  wav file output for stream group(s) enabled
  Telecom mode with -rN nominal rate enabled
  packet arrival times control packet push rate
00:00:00.000.017 mediaMin INFO: event log setup complete, log file target1561_session2331694_0000_event_log.txt, log level 8, cmd line /home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin -cx86 -i ./target1561_session2331694_0000.pcap -L -d0xc11 -r20
00:00:00.000.110 INFO: DSAssignPlatform() says system clock rate 2592.000 MHz, CPU architecture supports rdtscp instruction, TSC integrity monitoring enabled
00:00:00.000.196 INFO: DSAssignPlatform() says hwlib shared mem initialized, hPlatform handle 79413654 returned
00:00:00.000.222 INFO: DSConfigPktlib() uflags = 0x7
  P/M thread capacity  max sessions = 51, max groups = 17
  Event log            path = target1561_session2331694_0000_event_log.txt, uLogLevel = 8, uEventLogMode = 0x32, flush size = 1024, max size not set
  Debug                uDebugMode = 0x0, uPktStatsLogging = 0xd, uEnableDataObjectStats = 0x1
  Screen output        uPrintfLevel = 5, uPrintfControl = 0
  Energy saver         p/m thread energy saver inactivity time = 30000 msec, sleep time = 1000 usec
  Alarms               DSPushPackets packet cutoff alarm elapsed time not set, p/m thread preemption alarm elapsed time = 40 (msec)
00:00:00.000.494 INFO: DSConfigVoplib() voplib and codec libs initialized, flags = 0x19
00:00:00.000.507 INFO: DSConfigStreamlib() stream group library initialized
00:00:00.000.529 INFO: DSOpenPcap() opened pcap input file: ./target1561_session2331694_0000.pcap
Starting 1 packet and media processing threads
00:00:00.000.697 INFO: DSConfigMediaService() says pthread_setaffinity_np() set core 0 affinity for pkt/media thread 0 (thread id 0x7f7cf0673700), num online cores found = 16, uFlags = 0x1180101, pktlib.c:9782
x86 pkt/media start, pktlib, thread execution, thread id = 0x7f7cf0673700
00:00:00.000.807 INFO: first packet/media thread running, lib versions DirectCore v4.1.5 DEMO, pktlib v3.6.0 DEMO, streamlib v1.11.0 DEMO, voplib v1.6.13 DEMO-HC, alglib v1.2.6, diaglib v1.7.0
00:00:00.000.840 INFO: DSConfigMediaService() says setpriority() set Niceness to -15 for pkt/media thread 0
00:00:00.000.857 INFO: initializing packet/media thread 0, uFlags = 0x1180101, threadid = 0x7f7cf0673700, total num pkt/med threads = 1
lib_dbg_cfg.uPrintfLevel = 5
lib_dbg_cfg.uLogLevel = 8
lib_dbg_cfg.uPrintfControl = 0
lib_dbg_cfg.uEventLogMode = 0x32
lib_dbg_cfg.uEventLogFile = 0x0x660feb0
lib_dbg_cfg.uPktStatsLogging = 0xd
thread mode, nSessions_gbl = 0
Static session initialization: 0 sessions and 0 stream terminations
                                                Pkts recv 0%s   mnp -1 -1 -1 pd -1.00 -1.00 -1.00
Starting packet push-pull loop, press 'q' to exit, 'd' for real-time debug output, and other keys as described in online documentation
00:00:00.050.904 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090

[... many repetitions ...]

00:00:00.051.699 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:00.051.711 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
^^^^^^^ Creating dynamic session 1, input #1, auto-detected codec type EVS, auto-detected bitrate 24400, stream group target1561_session2331694_0000
        Creation packet info: IP ver 6, ssrc = 0xf499532f, seq num = 1, payload type 112, pkt len 122, RTP payload size 62, cat 4, rtp_pkt[0] 0x6, src port = 60300, dst_port = 1234
00:00:00.052.357 INFO: DSCreateSession() created stream group "target1561_session2331694_0000", idx = 0, owner session = 0, status = 1
00:00:00.052.390 INFO: DSCreateSession() attached term1 stream 0 to group "target1561_session2331694_0000", session = 0, status = 2
00:00:00.052.414 INFO: Initializing session 0
00:00:00.052.422 INFO: DSCreateSession() has assigned session 0 with flags 0xf02 and term1/2 flags 0x14f/0x14f to p/m thread 0 (which has 1 session and 1 stream group), and to stream group target1561_session2331694_0000 (0), owner session = 0, owner thread = 0
00:00:00.052.476 INFO: DSOpenPcap() opened pcap output file: target1561_session2331694_0000_jb0.pcap
00:00:00.052.514 INFO: DSOpenPcap() opened pcap output file: target1561_session2331694_0000_group0.pcap
00:00:00.052.527 INFO: First thread session input check, p/m thread = 0, fMediaThread = 1, i = 0, numSessions = 1
+++++++++Created dynamic session #1, total sessions created 1
look ahead pkts = 0, time = 0, chnums[0] = -1, chnums[1] = -1, hSession = 0, uFlags = 0xf02
numStreams = 0, numSessions = 1, numPkts = 0
chan_nums[0] = 0, num_chan = 3, hSession = 0, term = 0, input_buffer_interval = 20.00, output_buffer_interval = 20, ptime = 20, telecom mode, preemption monitoring enabled
channels 0 and 1 active for session 0, group chan = 2, calling DSGetOrderedPackets with SESSION_CHNUM flag
chan_nums[1] = 1, num_chan = 3, hSession = 0, term = 1, input_buffer_interval = 20.00, output_buffer_interval = 20, ptime = 20, telecom mode, preemption monitoring enabled
00:00:00.052.579 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:00.052.595 Received first packet for ch 0, p/m thread = 0
00:00:00.052.612        SSRC = 0xf499532f, SeqNum = 1, TimeStamp = 2880
00:00:00.052.596 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
00:00:00.052.625 INFO:  Chan 0 dynamic jitter buffer initial parameters (pkt count): min = 2, target = 10, max = 14
00:00:00.052.644 INFO: Dynamic jitter buffer calculated values (sample count): min = 640, target = 3200, max = 4480
00:00:00.052.640 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:00.052.657 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
00:00:00.052.665 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:00.052.673 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
00:00:00.052.679 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:00.052.687 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
Pushed pkts 1, pulled pkts 0ignoring UDP packet, dst port = 1235. To allow port use -pN option or add to NonDynamic_UDP_ignoring UDP packet, dst port = 1235. To allow port use -pN option or add to NonDynamic_UDP_Port_Allow_List[]
00:00:20.050.359 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090

[.. many repetitions ...]

00:00:23.051.082 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
00:00:23.051.093 WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090
00:00:23.051.104 WARNING: DSGetPacketInfo, error in parsing IPv6 extension headers
=== mediaMin INFO: input pcap[0] media time = 00:23
Flushing 1 session 0
/home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin: symbol lookup error: /lib/libevscom_sig.x86_gcc11.3.so: undefined symbol: _ZGVbN2v_acos
```

**Comment by signalogic** [comment]
Hi Ruben

[following assumes the Ubuntu container, if not let us know]

1) First, can you try rebuilding mediaMin:

 ```
cd /home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin
make clean
make all
```

there should be no build errors, and for the last step (link step), you should see:

`/usr/bin/g++ -flto -Xlinker -Map=mediaMin.map -Wl,--disable-new-dtags -Wl,-rpath=../../../../../SIG_LIBS/glibc -Wl,--no-as-needed timer.o getUserInterface.o cmdLineOpt.o types.o sdp.o utils.o reader.o writer.o keybd.o transcoder_control.o cmd_line_interface.o sdp_app.o session_app.o user_io.o mediaMin.o  -L../../../../../SIG_LIBS/glibc -L/usr/lib -o ./mediaMin -lstdc++ -lvoplib -levsenc_sig.x86_gcc11.3 -levsdec_sig.x86_gcc11.3 -levscom_sig.x86_gcc11.3 -lmelpe_sig.x86 -lg729ab_sig.x86 -lg726_sig.x86 -lamrdec_sig.x86 -lamrenc_sig.x86 -lamrwbdec_sig.x86 -lamrwbenc_sig.x86 -lpktlib -ldiaglib -lhwlib -lalglib -lstreamlib -lderlib -lcimlib -ldl -lpthread -lm -l:libmvec.so.1 -lstublib`

 " -levscom_sig.x86_gcc11.3" and "-l:libmvec.so.1" should appear as shown

2) the warning messages:

WARNING: get_ipv6_extension_header_length(), unsupported IPv6 extension header type found: 50, uFlags = 0x8000f010, pktlib.c,3090

are not good -- that's probably a clue as to why a run-time symbol lookup error occurs so far along in processing. Are you expecting more than the one EVS 24400 stream mediaMin is finding ? Can you anonymize target1561_session2331694_0000.pcap ** and e-mail to us ?  It only needs to be long enough for a few of those warnings to occur. We can fix that, give you an update, and see if the symbol error still occurs

** TraceWrangler works well for this. We have some instructions on using this if needed

**Comment by signalogic** [comment]
also let me ask - what is the underlying CPU type on which you're running the container ?  if you type:

`cat /proc/cpuinfo`

in the "flags" section, do you see "avx" ? the _ZGVbN2v_acos symbol is a vector acos() function which assumes AVX support. Possibly the container is limiting this or the underlying CPU doesn't have it (e.g. Celeron)

**Comment by smits** [comment]
avx is listed in the flags section, so all good there.  After rebuilding the error did not disappear.  Looking at the name of the library it seems that `-levscom_sig.x86_gcc11.3` is build with gcc version 11.3. while the gcc version inside of the container is 11.2, could that be a reason?:

**Comment by smits** [comment]
When running nm on `/lib/libevsenc_sig.x86_gcc11.3.so` I get:
```
# nm --dynamic /lib/libevscom_sig.x86_gcc11.3.so | grep acos
                 U _ZGVbN2v_acos
                 U _ZGVbN4v_acosf
                 U acos
```
Running ldd gives me:
```
# ldd /lib/libevscom_sig.x86_gcc11.3.so
        linux-vdso.so.1 (0x00007fffa6286000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69ebd31000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f69ec062000)
```

libc does not define this symbol.

libm is linked into the resulting executable mediaMin but not with the exact same referenced mangled symbol name:
```
# nm --dynamic /lib/x86_64-linux-gnu/libm.so.6 | grep acos
00000000000249e0 i __acos_finite
000000000004eab0 T __acosf128_finite
00000000000415d0 T __acosf_finite
0000000000022530 T __acosh_finite
000000000004f560 T __acoshf128_finite
00000000000418b0 T __acoshf_finite
0000000000014520 T __acoshl_finite
0000000000014500 T __acosl_finite
000000000000fb60 W acos
0000000000013400 W acosf
0000000000074770 W acosf128
0000000000013400 W acosf32
000000000000fb60 W acosf32x
[...]
```
So it seems that library is compiled with another library defining acos but not linked with it.

**Comment by smits** [comment]
I figured out which library contains this symbol:

```
root@e563050f62af:/home/sigsrf_sdk_demo/Signalogic# nm --dynamic SIG_LIBS/glibc/libmvec.so.1 | grep acos
0000000000005ae0 i _ZGVbN2v_acos
0000000000005b10 i _ZGVbN2v_acosh
00000000000072b0 i _ZGVbN4v_acosf
00000000000072e0 i _ZGVbN4v_acoshf
0000000000006500 T _ZGVcN4v_acos
0000000000006540 T _ZGVcN4v_acosh
0000000000007cd0 T _ZGVcN8v_acosf
0000000000007d10 T _ZGVcN8v_acoshf
0000000000005ff0 i _ZGVdN4v_acos
0000000000006020 i _ZGVdN4v_acosh
00000000000077c0 i _ZGVdN8v_acosf
00000000000077f0 i _ZGVdN8v_acoshf
0000000000008540 i _ZGVeN16v_acosf
0000000000008570 i _ZGVeN16v_acoshf
0000000000006ce0 i _ZGVeN8v_acos
0000000000006d10 i _ZGVeN8v_acosh
                 U acos
                 U acosf
                 U acosh
                 U acoshf
```

But the version of libmvec to which the executable is linked does not define it:

```
root@e563050f62af:/home/sigsrf_sdk_demo/Signalogic# ldd /home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin
        linux-vdso.so.1 (0x00007ffdf2f42000)
        libstdc++.so.6 => /gcc/lib64/libstdc++.so.6 (0x00007f420eadd000)
        libvoplib.so.1.3.3 => /lib/libvoplib.so.1.3.3 (0x00007f420e8c5000)
        libevsenc_sig.x86_gcc11.3.so => /lib/libevsenc_sig.x86_gcc11.3.so (0x00007f420e7ff000)
        libevsdec_sig.x86_gcc11.3.so => /lib/libevsdec_sig.x86_gcc11.3.so (0x00007f420e761000)
        libevscom_sig.x86_gcc11.3.so => /lib/libevscom_sig.x86_gcc11.3.so (0x00007f420e627000)
        libmelpe_sig.x86.so => /lib/libmelpe_sig.x86.so (0x00007f420e37c000)
        libg729ab_sig.x86.so => /lib/libg729ab_sig.x86.so (0x00007f420e15d000)
        libg726_sig.x86.so => /lib/libg726_sig.x86.so (0x00007f420df56000)
        libamrdec_sig.x86.so => /lib/libamrdec_sig.x86.so (0x00007f420dd37000)
        libamrenc_sig.x86.so => /lib/libamrenc_sig.x86.so (0x00007f420db09000)
        libamrwbdec_sig.x86.so => /lib/libamrwbdec_sig.x86.so (0x00007f420d8ec000)
        libamrwbenc_sig.x86.so => /lib/libamrwbenc_sig.x86.so (0x00007f420d6c2000)
        libpktlib.so.3.0.1 => /lib/libpktlib.so.3.0.1 (0x00007f42099ba000)
        libdiaglib.so.1.5.0 => /lib/libdiaglib.so.1.5.0 (0x00007f42097ad000)
        libhwlib.so.4.1.1 => /lib/libhwlib.so.4.1.1 (0x00007f4208c90000)
        libalglib.so.1.2.1 => /lib/libalglib.so.1.2.1 (0x00007f4208a8a000)
        libstreamlib.so.1.8.8 => /lib/libstreamlib.so.1.8.8 (0x00007f42061e9000)
        libderlib.so.1.0.0 => /lib/libderlib.so.1.0.0 (0x00007f4205fbd000)
        libcimlib.so => /lib/libcimlib.so (0x00007f4205da4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4205d9e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4205d7b000)
        libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f4205d4f000)
        libstublib.so => /lib/libstublib.so (0x00007f4205b48000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f42059f9000)
        libgcc_s.so.1 => /gcc/lib64/libgcc_s.so.1 (0x00007f42059de000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f42057ec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f420ecf7000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f42057e2000)
root@e563050f62af:/home/sigsrf_sdk_demo/Signalogic# nm --dynamic /lib/x86_64-linux-gnu/libmvec.so.1 | grep acos
```
So maybe it is just about not setting the LD_LIBRARY_PATH correctly?

**Comment by smits** [comment]
When adding the SIG_LIBS/glibc to the LD_LIBRARY_PATH the undefined symbol disappears:
```
 export LD_LIBRARY_PATH=/home/sigsrf_sdk_demo/Signalogic/SIG_LIBS/glibc/:$LD_LIBRARY_PATH
```

**Comment by signalogic** [comment]
wow that's excellent sleuthing. The mediaMin Makefile links with

`  Wl,-rpath=$(INSTALLPATH)/SIG_LIBS/glibc`

which we thought would ensure the SIG_LIBS/glibc version of libmvec would get linked. But it seems a different version got picked up instead. If you run

`  ldd --version`

which GLIBC version is on your system?

Also I think we fixed the warning messages -- it looks like your pcap has some IPv6 packets with ESP (encapsulated security payload) packets, which mediaMin should ignore. Would you like an updated container ?

**Comment by smits** [comment]
> wow that's excellent sleuthing. The mediaMin Makefile links with
> 
> ` Wl,-rpath=$(INSTALLPATH)/SIG_LIBS/glibc`
> 
> which we thought would ensure the SIG_LIBS/glibc version of libmvec would get linked. But it seems a different version got picked up instead. If you run
> 
> ` ldd --version`
> 
> which GLIBC version is on your system?
```
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.15) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
Remember that this is from within the container you provide.
> 
> Also I think we fixed the warning messages -- it looks like your pcap has some IPv6 packets with ESP (encapsulated security payload) packets, which mediaMin should ignore. Would you like an updated container ?

That would be appreciated. Thanks.

**Comment by signalogic** [comment]
> When adding the SIG_LIBS/glibc to the LD_LIBRARY_PATH the undefined symbol disappears

Did you have to rebuild after this ? or just run ?

After further reviewing your comments, I would lilke to check if mediaMin may have built differently on your container than on ours. In the link step did you see "-Wl,-rpath=../../../../../SIG_LIBS/glibc" and "-l:libmvec.so.1"  ? Also could you let me know your LD_LIBRARY_PATH contents ?

> Remember that this is from within the container you provide.

Interestingly inside our test containers we see:

`  ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31`

which is a slight difference from ldd output on your container. I know containers share Linux kernels with their host, but I would have thought the GLIBC filesystem should not vary

Thanks

**Comment by signalogic** [comment]
Hi Ruben, an updated Ubuntu container is uploaded. Hopefully it will not show the ESP packet warnings, although we don't have a pcap to test that yet. We also made a slight change to mediaMin link order that might get the correct libmvec linked, although that's just an educated guess at this point.

Can I ask after you pull the container, before you run it can you do

`  docker images --digests`

and let us know the md5 sum you see ? Also immediately after running the container, can you run ldd --version and let us know if it's any different than the result you gave previously ? I want to verify that we are in fact seeing different ldd results for the same identical container. Thanks

One other note of interest - the _ZGVbN2v_acos symbol results from an acos() call inside an AMR-WB IO compatibility mode decode function, so your test pcap must have some AMR-WB IO mode packets that showed up late in the stream

**Comment by smits** [comment]
```
$ docker images --digests
REPOSITORY                                                                           TAG             DIGEST                                                                    IMAGE ID       CREATED         SIZE
signalogic/sigsrf_sdk_demo_ubuntu                                                    latest          sha256:addef308646cf9c9848bd929bdebe472b5166c0bcb8e2adf1e1018f9a5fb122b   2b40182c857a   12 hours ago    15.7GB
```
It seems that libmvec still not properly linked:
```
root@4b57d11305d2:/home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin# ldd ./mediaMin
        [...]
        libmvec.so.1 => ../../../../../SIG_LIBS/glibc/libmvec.so.1 (0x00007ff19ea69000)
        [...]
root@0bd78c883af7:~# ldd /home/sigsrf_sdk_demo/Signalogic/apps/mediaTest/mediaMin/mediaMin
       [...]
        libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f40822cf000)
[...]
```
This is because the rpath is set using a relative path, it should be an absolute path instead: https://stackoverflow.com/questions/38058041/correct-usage-of-rpath-relative-vs-absolute 


ldd looks different in the new container and is not the some version as on the host:
```
X@Y:~$ docker run -it --cap-add=sys_nice signalogic/sigsrf_sdk_demo_ubuntu /bin/bash
root@5ac45db68dd5:/# ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
root@5ac45db68dd5:/# exit
X@Y:~$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.7) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by signalogic** [comment]
ok I see now. I missed this in your first post:

`  mediaMin/mediaMin -cx86 -i ./pcaps/EVS_16khz_13200bps_CH_PT127_IPv4.pcap -L -d0xc11`

so the run wasn't from the mediaMin folder -- easy to reproduce if I was just paying attention. We'll get this fixed and thanks very much for the stackoverflow link.

Your container md5 sum matches what I see, and ldd version now, too. I guess that one counts as a goose chase.

Do the ESP payload packet warnings go away ?

**Comment by smits** [comment]
The warnings disappeared, but it was a faulty pcap containing lots of unrelated packets.

**Comment by signalogic** [comment]
Ok that's good, thanks for the update.  It shouldn't matter what pcap is given to mediaMin -- it's supposed to handle it.  We'll do another container update to fix the libmvec rpath

**Comment by signalogic** [comment]
updated container available, tested running mediaMin and mediaTest from different folders. Seems to work 😃

**Comment by signalogic** [comment]
Hi Ruben, please let us know if we can close this. Also as a note if you have HI2/HI3 format files, there are some [command line examples](https://github.com/signalogic/SigSRF_SDK/blob/master/mediaTest_readme.md#user-content-hi2_hi3_stream_and_openli_support) on the Github page

**Comment by smits** [comment]
All is working fine with the updated container.  Thanks for the link to the cli examples.
